### ISSUE TITLE
How can i install this extension?

### ISSUE THREAD

**Issue by daywalker90** [lnbits/free-lnaddress-extension#1]
Hi i was waiting for this extension, thank you for making it !
How can i install it? I don't see it in this repository: https://github.com/lnbits/lnbits-extensions/
and this extension doesn't have it's own repository either?

**Comment by bitkarrot** [comment]
@daywalker90, right now, it seems we are waiting for @arcbtc to finalize the new manifest system for lnbits extensions. I don't know what the status is, perhaps he can let us know. 

The repository is here github.com/lnbits/free-lnaddress-extension

The Draft PR is here: https://github.com/lnbits/lnbits/pull/1319

**Comment by daywalker90** [comment]
I meant lnbits extension repository not github repository, slightly confusing :).Ok so the plan is to get it into the "official" extension repository and i'm just too early got it.

**Comment by bitkarrot** [comment]
@daywalker90 if you don't want to wait for the merge (because it might take quite a while right now) you are also free to manually install the extension into your current lnbits, and this should work for now

Just follow the instructions here: 

https://github.com/bitkarrot/free-lnaddress-lnbits
