### ISSUE TITLE
/.well-known/lnurlp/{username} no longer resolves

### ISSUE THREAD

**Issue by benjaminchodroff** [lnbits/free-lnaddress-extension#4]
I am using a fresh install of the latest lnbits docker 0.10 + nginx, and version 0.0.2 release of this plugin, but I am unable to get a lnaddress to work. I also tried to use the 0.0.1 release of this plugin, but it fails to install in the latest version of lnbits. 

I see that # @core_app.get("/.well-known/lnurlp/{username}") has been commented out. I am new to lnaddress but I believe this endpoint is required, as I can see 404 responses coming when I attempt to use the plugin. Is there some sort of nginx reverse proxy configuration I should be doing to redirect traffic to another api endpoint? Any example or pointers are greatly appreciated.

**Comment by bitkarrot** [comment]
this extension only works with older version of LNBits (pre-feb 2023). you can use this extension with modifications written in the release notes.  

current changes in the core are pending and will take time to resolve for older extensions
